version: '3.9'

services:

  www:
    image: webdevops/php-apache:alpine-php7
    container_name: Web_Aplication
    ports:
      - '80:80'
    volumes:
      - www_data:/app
    networks:
      - public
  
  database:
    image: mysql:5.7
    container_name: DataBase_Aplication
    environment:
      - MYSQL_DATABASE=Tasks
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - public

volumes:
  www_data:
  database_data:
  
networks:
  public:
    driver: bridge