apiVersion: v1
kind: Pod
metadata:
  name: my-web-app-php
  labels:
    app: my-web-app-php
spec:
  containers:
  - name: my-web-app-php
    image: denilsonbonatti/myapp-php:1.0
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-web-app-php-service
spec:
  type: NodePort
  selector:
    app: my-web-app-php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001