apiVersion: v1
kind: Pod
metadata:
  name: my-web-app-php
  labels:
    app: my-web-app-php
spec:
  containers:
  - name: my-web-app-php
    image: denilsonbonatti/myapp-php:1.0
    ports:
    - containerPort: 80